import { useState, useEffect, useRef } from 'react';
import api from '../api';
import { useAuth } from '../context/AuthContext';
import ExpenseModal from '../components/ExpenseModal';
import * as XLSX from 'xlsx';

const fmt = n => '৳' + Number(n || 0).toLocaleString('en-BD', { minimumFractionDigits: 2 });
const fmtDate = d => d ? new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

const CAT_LABELS = {
  transportation: 'Transportation', printing_stationery: 'Printing & Stationery',
  field_work: 'Field Work', communication: 'Communication', miscellaneous: 'Miscellaneous',
};
const CAT_BADGE = {
  transportation: 'badge-teal', printing_stationery: 'badge-indigo',
  field_work: 'badge-green', communication: 'badge-amber', miscellaneous: 'badge-gray',
};

export default function Expenses() {
  const { isAdmin, user } = useAuth();
  const [expenses, setExpenses] = useState([]);
  const [projects, setProjects] = useState([]);
  const [members, setMembers]   = useState([]);
  const [loading, setLoading]   = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [filters, setFilters]   = useState({ project_id: '', user_id: '', reimbursed: '', category: '', from_date: '', to_date: '' });
  const tableRef = useRef(null);

  const load = async () => {
    const params = Object.fromEntries(Object.entries(filters).filter(([, v]) => v !== ''));
    try {
      const [eRes, pRes] = await Promise.all([api.get('/expenses', { params }), api.get('/projects')]);
      setExpenses(eRes.data); setProjects(pRes.data);
      if (isAdmin) { const uRes = await api.get('/auth/users'); setMembers(uRes.data); }
    } catch(e) { console.error(e); } finally { setLoading(false); }
  };

  useEffect(() => { load(); }, [JSON.stringify(filters)]);

  const handleDelete = async id => {
    if (!confirm('Delete this expense? This action cannot be undone.')) return;
    try { await api.delete(`/expenses/${id}`); load(); } catch(e) { alert(e.response?.data?.error || 'Could not delete.'); }
  };

  const totals = expenses.reduce((a, e) => ({
    total: a.total + Number(e.amount),
    reimbursed: a.reimbursed + (e.reimbursed ? Number(e.amount) : 0),
    pending: a.pending + (!e.reimbursed ? Number(e.amount) : 0),
  }), { total: 0, reimbursed: 0, pending: 0 });

  const setF = (k, v) => setFilters(f => ({ ...f, [k]: v }));
  const hasF = Object.values(filters).some(v => v !== '');

  const handleExportCSV = () => {
    const headers = ['Date', 'Project', 'Member', 'Category', 'Description', 'Amount', 'Status', 'Reimbursed From'];
    const rows = expenses.map(e => [
      fmtDate(e.expense_date), e.project_code, e.submitted_by_name,
      CAT_LABELS[e.category], `"${e.description}"`,
      Number(e.amount).toFixed(2),
      e.reimbursed ? 'Reimbursed' : 'Pending',
      e.reimbursed_from || '',
    ]);
    const csv = [headers, ...rows].map(r => r.join(',')).join('\n');
    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }));
    a.download = `expenses-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
  };

  const handlePrint = () => window.print();
  const handleExportXLSX = () => {
    const wb = XLSX.utils.book_new();
    
    // Summary sheet
    const summaryData = [
      ['RESEARCH EXPENSE TRACKER - EXPENSE REPORT'],
      ['Generated', new Date().toLocaleString()],
      ['Generated by', user?.name || 'User'],
      [],
      ['EXPENSE SUMMARY'],
      ['Total Expenses', totals.total],
      ['Total Reimbursed', totals.reimbursed],
      ['Total Pending', totals.pending],
      ['Reimbursement Rate (%)', ((totals.reimbursed / totals.total) * 100).toFixed(2)],
    ];
    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');
    
    // Detailed expenses sheet
    const expenseData = [
      ['Date', 'Project Code', 'Project Name', 'Member', 'Category', 'Description', 'Amount (BDT)', 'Status', 'Reimbursed From'],
      ...expenses.map(e => [
        fmtDate(e.expense_date),
        e.project_code,
        e.project_name,
        e.submitted_by_name,
        CAT_LABELS[e.category],
        e.description,
        Number(e.amount),
        e.reimbursed ? 'Reimbursed' : 'Pending',
        e.reimbursed_from || '—',
      ]),
      [],
      ['TOTAL', '', '', '', '', '', totals.total, '', ''],
    ];
    const expenseSheet = XLSX.utils.aoa_to_sheet(expenseData);
    expenseSheet['!cols'] = [{wch: 12}, {wch: 12}, {wch: 18}, {wch: 15}, {wch: 15}, {wch: 25}, {wch: 15}, {wch: 12}, {wch: 12}];
    XLSX.utils.book_append_sheet(wb, expenseSheet, 'Expenses');
    
    XLSX.writeFile(wb, `expenses-report-${new Date().toISOString().split('T')[0]}.xlsx`);
  };


  return (
    <>
      <div className="page-header">
        <div className="page-header-left">
          <div className="page-eyebrow">Financial Records</div>
          <h1 className="page-title">Expenses</h1>
          <p className="page-subtitle">
            {expenses.length} record{expenses.length !== 1 ? 's' : ''}
            {hasF ? ' · filtered' : ' · all records'}
          </p>
        </div>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }} className="no-print">
          <div className="export-bar">
            <button className="btn btn-outline btn-sm" onClick={handleExportCSV}>⬇ Export CSV</button>
            <button className="btn btn-outline btn-sm" onClick={handleExportXLSX}>📊 Export XLSX</button>
            <button className="btn btn-outline btn-sm" onClick={handlePrint}>🖨 Print</button>
          </div>
          <button className="btn btn-primary" onClick={() => setShowModal(true)}>+ Submit Expense</button>
        </div>
      </div>

      <div className="page-body">
        {/* Summary */}
        <div className="stats-grid" style={{ gridTemplateColumns: 'repeat(3,1fr)', marginBottom: 20 }}>
          <div className="stat-card">
            <div className="stat-top">
              <div><div className="stat-label">Total (filtered)</div><div className="stat-value indigo">{fmt(totals.total)}</div></div>
              <div className="stat-icon si-indigo">💳</div>
            </div>
            <div className="stat-note">{expenses.length} expense{expenses.length !== 1 ? 's' : ''}</div>
          </div>
          <div className="stat-card">
            <div className="stat-top">
              <div><div className="stat-label">Reimbursed</div><div className="stat-value green">{fmt(totals.reimbursed)}</div></div>
              <div className="stat-icon si-green">✅</div>
            </div>
            <div className="stat-note">{expenses.filter(e => e.reimbursed).length} paid</div>
          </div>
          <div className="stat-card">
            <div className="stat-top">
              <div><div className="stat-label">Pending</div><div className="stat-value amber">{fmt(totals.pending)}</div></div>
              <div className="stat-icon si-amber">⏳</div>
            </div>
            <div className="stat-note">{expenses.filter(e => !e.reimbursed).length} unpaid</div>
          </div>
        </div>

        {/* Filters */}
        <div className="card no-print" style={{ marginBottom: 20 }}>
          <div className="card-header">
            <span className="card-title">Filter Expenses</span>
            {hasF && <button className="btn btn-ghost btn-sm" onClick={() => setFilters({ project_id: '', user_id: '', reimbursed: '', category: '', from_date: '', to_date: '' })}>✕ Clear all</button>}
          </div>
          <div className="filter-bar">
            <div className="filter-field">
              <label className="form-label">Project</label>
              <select className="form-select" value={filters.project_id} onChange={e => setF('project_id', e.target.value)}>
                <option value="">All projects</option>
                {projects.map(p => <option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}
              </select>
            </div>
            {isAdmin && (
              <div className="filter-field">
                <label className="form-label">Member</label>
                <select className="form-select" value={filters.user_id} onChange={e => setF('user_id', e.target.value)}>
                  <option value="">All members</option>
                  {members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}
                </select>
              </div>
            )}
            <div className="filter-field">
              <label className="form-label">Category</label>
              <select className="form-select" value={filters.category} onChange={e => setF('category', e.target.value)}>
                <option value="">All categories</option>
                {Object.entries(CAT_LABELS).map(([v, l]) => <option key={v} value={v}>{l}</option>)}
              </select>
            </div>
            <div className="filter-field">
              <label className="form-label">Status</label>
              <select className="form-select" value={filters.reimbursed} onChange={e => setF('reimbursed', e.target.value)}>
                <option value="">All</option>
                <option value="false">Pending only</option>
                <option value="true">Reimbursed only</option>
              </select>
            </div>
            <div className="filter-field">
              <label className="form-label">From Date</label>
              <input type="date" className="form-input" value={filters.from_date} onChange={e => setF('from_date', e.target.value)} />
            </div>
            <div className="filter-field">
              <label className="form-label">To Date</label>
              <input type="date" className="form-input" value={filters.to_date} onChange={e => setF('to_date', e.target.value)} />
            </div>
          </div>
        </div>

        {/* Table */}
        <div className="card" ref={tableRef}>
          <div className="card-header">
            <span className="card-title">Expense Records</span>
            <span className="card-meta">{expenses.length} entries</span>
          </div>
          {loading ? (
            <div style={{ padding: 48, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14 }}>
              <div className="spinner" /><div className="loading-label">Loading records…</div>
            </div>
          ) : expenses.length === 0 ? (
            <div className="empty-state">
              <div className="empty-icon">🧾</div>
              <h4>No expenses found</h4>
              <p>No expense records match the current filters. Try adjusting your filters or submit a new expense.</p>
            </div>
          ) : (
            <div className="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Project</th>
                    {isAdmin && <th>Submitted By</th>}
                    <th>Category</th>
                    <th>Description</th>
                    <th style={{ textAlign: 'right' }}>Amount</th>
                    <th>Status</th>
                    {isAdmin && <th>Source</th>}
                    <th className="no-print"></th>
                  </tr>
                </thead>
                <tbody>
                  {expenses.map(e => (
                    <tr key={e.id}>
                      <td className="td-date">{fmtDate(e.expense_date)}</td>
                      <td>
                        <div style={{ marginBottom: 2 }}><span className="td-code">{e.project_code}</span></div>
                        <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{e.project_name}</div>
                      </td>
                      {isAdmin && (
                        <td>
                          <div style={{ fontWeight: 600, fontSize: 13 }}>{e.submitted_by_name}</div>
                          {e.reimbursed && <div style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>Paid {fmtDate(e.reimbursed_at)}</div>}
                        </td>
                      )}
                      <td><span className={`badge ${CAT_BADGE[e.category] || 'badge-gray'}`}>{CAT_LABELS[e.category]}</span></td>
                      <td style={{ maxWidth: 220 }}>
                        <div style={{ fontSize: 13, fontWeight: 500 }}>{e.description}</div>
                        {e.receipt_note && <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginTop: 2 }}>{e.receipt_note}</div>}
                      </td>
                      <td className="td-amount">{fmt(e.amount)}</td>
                      <td>{e.reimbursed ? <span className="badge badge-green">✓ Reimbursed</span> : <span className="badge badge-amber">Pending</span>}</td>
                      {isAdmin && <td style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{e.reimbursed ? (e.reimbursed_from === 'university' ? 'University' : 'Project') : '—'}</td>}
                      <td className="no-print">
                        {!e.reimbursed && (isAdmin || e.submitted_by === user?.id) && (
                          <button className="btn btn-ghost btn-xs" onClick={() => handleDelete(e.id)}
                            style={{ color: 'var(--danger)' }}>Remove</button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr>
                    <td colSpan={isAdmin ? 5 : 4} style={{ color: 'var(--text-secondary)' }}>Total · {expenses.length} records</td>
                    <td className="td-amount">{fmt(totals.total)}</td>
                    <td colSpan={isAdmin ? 3 : 2}>
                      <span style={{ color: 'var(--success)', fontWeight: 700 }}>{fmt(totals.reimbursed)}</span>
                      <span style={{ color: 'var(--text-tertiary)', margin: '0 8px' }}>·</span>
                      <span style={{ color: 'var(--warning)', fontWeight: 700 }}>{fmt(totals.pending)} pending</span>
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          )}
        </div>
      </div>

      {showModal && <ExpenseModal onClose={() => setShowModal(false)} onSaved={() => { setShowModal(false); load(); }} />}
    </>
  );
}
