import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import api from '../api';

export default function Settings() {
  const { user, workspaceName, reportHeader, updateUser } = useAuth();
  const [form, setForm]   = useState({ name: workspaceName, report_header: reportHeader });
  const [msg, setMsg]     = useState({ type: '', text: '' });
  const [saving, setSaving] = useState(false);

  const handleSave = async e => {
    e.preventDefault(); setMsg({ type: '', text: '' }); setSaving(true);
    try {
      const { data } = await api.patch('/auth/workspace', form);
      updateUser({ workspace_name: data.name, report_header: data.report_header });
      setMsg({ type: 'success', text: 'Workspace settings saved.' });
    } catch (err) {
      setMsg({ type: 'error', text: err.response?.data?.error || 'Failed to save.' });
    } finally { setSaving(false); }
  };

  return (
    <>
      <div className="page-header">
        <div className="page-header-left">
          <div className="page-eyebrow">Administration</div>
          <h1 className="page-title">Workspace Settings</h1>
          <p className="page-subtitle">Controls how your workspace appears across the app and in reports</p>
        </div>
      </div>

      <div className="page-body">
        <div className="card" style={{ maxWidth: 560 }}>
          <div className="card-header"><span className="card-title">Workspace Identity</span></div>
          <div className="card-body">
            {msg.text && (
              <div className={`notice notice-${msg.type === 'success' ? 'success' : 'error'}`}
                style={{ marginBottom: 16 }}>
                {msg.type === 'success' ? '✓' : '⚠'} {msg.text}
              </div>
            )}
            <form onSubmit={handleSave}>
              <div className="form-group">
                <label className="form-label">Workspace Name</label>
                <input className="form-input"
                  value={form.name}
                  onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
                  required />
                <div className="form-hint">
                  Your private workspace name. Shown in the sidebar and app header.
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Report Header</label>
                <input className="form-input"
                  placeholder="e.g. FGS, DIU  or  CSE Department, BUET"
                  value={form.report_header}
                  onChange={e => setForm(f => ({ ...f, report_header: e.target.value }))} />
                <div className="form-hint">
                  Appears at the top of all exported reports and PDFs.
                  Change this to match your department or institution.
                  If blank, workspace name is used.
                </div>
              </div>

              {/* Live preview */}
              <div style={{
                border: '1px solid var(--border)', borderRadius: 8,
                overflow: 'hidden', marginBottom: 20,
              }}>
                <div style={{
                  background: '#0d1f17', color: '#28e98c',
                  padding: '8px 14px', fontSize: 11, fontWeight: 700,
                  textTransform: 'uppercase', letterSpacing: '0.08em',
                }}>
                  Report preview
                </div>
                <div style={{ padding: '12px 14px', background: 'var(--bg-surface)' }}>
                  <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 4 }}>
                    {form.report_header || form.name || 'Your workspace name'}
                  </div>
                  <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-primary)' }}>
                    Project Expense Report
                  </div>
                  <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginTop: 4 }}>
                    Generated by ResearchTrack
                  </div>
                </div>
              </div>

              <button type="submit" className="btn btn-primary" disabled={saving}>
                {saving ? 'Saving…' : 'Save Changes'}
              </button>
            </form>
          </div>
        </div>

        <div className="card" style={{ maxWidth: 560, marginTop: 20 }}>
          <div className="card-header"><span className="card-title">Workspace Info</span></div>
          <div className="card-body">
            <div className="info-grid">
              <div className="info-card indigo">
                <div className="info-card-title">🔒 Data Privacy</div>
                <div className="info-card-body">
                  Your workspace is completely private. No other user, department, or organization
                  can see your projects or expenses.
                </div>
              </div>
              <div className="info-card green">
                <div className="info-card-title">👤 Admin</div>
                <div className="info-card-body">
                  You are the admin of this workspace. You can add team members,
                  create projects, and manage all expenses.
                </div>
              </div>
              <div className="info-card amber">
                <div className="info-card-title">📧 Email</div>
                <div className="info-card-body">
                  {user?.email} — this is the account owner email.
                  Contact support if you need to change it.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
